### ISSUE TITLE
Automated e2e tests

### ISSUE THREAD

**Issue by mschwoer** [MannLabs/alphadia#140]
WHO
Devs

WHAT
Have automated end-to-end tests

WHY
Avoid regression, check performance

Acceptance Criteria
- on every merge to develop, alphaDIA is run in a github custom runner with a defined data set
- metrics are computed from the results and uploaded to neptune

Additional information
- for now: 1 test case, few metrics
- make adding new test cases easy

**Comment by tobiasko** [comment]
Please add diaPASEF test case

**Comment by mschwoer** [comment]
> Please add diaPASEF test case

will be added, I put this on our internal project board (https://github.com/orgs/MannLabs/projects/12/views/1?pane=issue&itemId=66339006)
