### ISSUE TITLE
ERROR: Workflow failed for ..... with error No objects to concatenate

### ISSUE THREAD

**Issue by Andre-C-M** [MannLabs/alphadia#176]
**Describe the bug**
Fantastic App! Maybe just a setting issue: Running timsTOF DIA files with predicted DIANN library runs through, using the alphadia prediction causes 'no objects to concatenate' error though. Logfiles attached.
thx!

**To Reproduce**
sent you the files for reproduction

**Logs**
Please provide the log (see the AlphaDIA terminal on where to find it).

**Additional context**
Add any other context about the problem here. Attached log files or upload data files if possible.
[log.txt](https://github.com/MannLabs/alphadia/files/15466799/log.txt)

**Comment by JoergDoellinger** [comment]
Hi, 

I receive the same error with my timsTOF diaPASEF data.

best

**Comment by DenysOliinyk** [comment]
Hi, 
Encountering same error for diaPASEF data. 
[log.txt](https://github.com/user-attachments/files/15537043/log.txt)

**Comment by tobiasko** [comment]
Me tooo! All my diaPASEF files fail with this error. Already filed an issue. Is alphadia not running any CI tests on the stable release?

**Comment by GeorgWa** [comment]
Hi, can you describe the library and send the log for which you have experienced this issue?

This hasnt appeared in our library based tests so far and is most likely due to a 1) malformed library or 2) fully predicted library which is not yet fully supported on the timstof.

**Comment by tobiasko** [comment]
see essue #208 for details

**Comment by GeorgWa** [comment]
Hi, 
[Here](https://datashare.biochem.mpg.de/s/rFyL0WBdn7zSJop) you can find some basic HeLa test data including a diaPASEF library. Please let me know if you can process your data with this library.

This issue has two components: 
1. AlphaDIA should be able to process .d data wit empirical libraries as well as predicted libraries. We will provide a fix for the bug which should enable processing.

2. The feature free processing algorithm is very sensitive and flexible (diaPASEF, synchroPASEF, midiaPASEF, slicePASEF) but also not the fastest for large libraries. I've updated the Readme to reflect this better. We have been working towards a prototype for the first pass but have decided to focus mostly on the Astral for now.

**Comment by JoergDoellinger** [comment]
Hi,

thanks for your quick reply. I am able to process my data with your library and also with a predicted .tsv library from DiaNN.

**Comment by GeorgWa** [comment]
The first point has been addressed in #213 and will be part of the next version.

**Comment by michaelsteidel86** [comment]
Hi,

do you have an estimate when the diaPASEF bug will be fixed, resulting in this "No objects to concatenate" error?

Thanks in advance!
Michael

**Comment by GeorgWa** [comment]
It's already available in the development install. We will most likely do a new release this week.
