### ISSUE TITLE
ERROR: module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by ZhaoYaniBruker** [MannLabs/alphadia#205]
**Describe the bug**
see the enclosed screenshot. (I use the windows version of alphaDIA).
![Screenshot 2024-06-04 101540](https://github.com/MannLabs/alphadia/assets/147511279/a4ae9f1a-a48f-4cb8-960b-2e8f825e11d1)

**Comment by jalew188** [comment]
This will be fixed in the next version #201

**Comment by mschwoer** [comment]
Is fixed in this release https://github.com/MannLabs/alphadia/releases/tag/v1.6.2
