### ISSUE TITLE
Which specLib formats are supported by alphabase

### ISSUE THREAD

**Issue by tobiasko** [MannLabs/alphadia#209]
Hi developers,

which specLib formats are currently supported by alphabase? The alphaDIA manuscript just talks about spectral libraries in .tsv format...which could be just anything. Which columns are required? I tried a lib generated by DIA-NN, this did not work. How about libs generated by other tools like Spectronaut? Are predicted libs from tools like Koina ok?

**Comment by tobiasko** [comment]
ok. THX!

**Comment by tobiasko** [comment]
Where can I find a description of your supported .tsv library format?

**Comment by GeorgWa** [comment]
Hi, 

DIA-NN, MSFragger and Spectraonaut spectral libraries should be supported. Furthermore alphaBase HDF. If you have a DIA-NN .tsv library which does not work, please let us know and send the library. We are happy to fix it and include in our test suite.
