### ISSUE TITLE
synchro-PASEF support?

### ISSUE THREAD

**Issue by tobiasko** [MannLabs/alphadia#211]
Dear alphadia developers,

your preprint promises support for synchro-PASEF data - even with variable isolation windows. Given what I have experienced with traditional dia-PASEF data I am bit hesitant to try. Is it really fully supported yet? Which parameters are crucial?

Best,
Tobi

**Comment by GeorgWa** [comment]
Hi,

Library based searches of synchroPASEF data are possible. The same limitations as diaPASEF apply. If you would like to try it and see the optimal settings, have a look at this testcase: https://github.com/MannLabs/alphadia/blob/c6f3092ab9163e6b3bf7d3af201d6fb4d500d4db/tests/e2e_tests/e2e_test_cases.yaml#L38

You can directly download the files mentioned in the testcase.
