### ISSUE TITLE
Workflow abruptly stops

### ISSUE THREAD

**Issue by nurudeen95** [MannLabs/alphadia#234]
I am trying AlphaDIA for the first time for 72 .raw files for a library free search. However, when I start the run, it stops within seconds with the following report below:

Method Setup
CPU: 0.69%
RAM: 11.48 GB / 63.63 GB (18.05%)
Unknown arguments: ['A\\20240416_ZOEIb_20240329_ProjectA_Serum\\Samples\\AlphaDIA_Report_061724\\config.yaml']
usage: alphadia.exe [-h] [--version] [--output [OUTPUT]] [--file FILE]
                    [--directory DIRECTORY] [--regex [REGEX]]
                    [--library [LIBRARY]] [--fasta FASTA] [--config [CONFIG]]
                    [--wsl] [--config-dict [CONFIG_DICT]]

Search DIA experiments with alphaDIA

options:
  -h, --help            show this help message and exit
  --version, -v         Print version and exit
  --output [OUTPUT], -o [OUTPUT]
                        Output directory
  --file FILE, -f FILE  Raw data input files.
  --directory DIRECTORY, -d DIRECTORY
                        Directory containing raw data input files.
  --regex [REGEX], -r [REGEX]
                        Regex to match raw files in directory.
  --library [LIBRARY], -l [LIBRARY]
                        Spectral library.
  --fasta FASTA         Fasta file(s) used to generate or annotate the
                        spectral library.
  --config [CONFIG], -c [CONFIG]
                        Config yaml which will be used to update the default
                        config.
  --wsl, -w             Set if running on Windows Subsystem for Linux.
  --config-dict [CONFIG_DICT]
                        Python Dict which will be used to update the default
                        config.
WARNING:root:WARNING: Temp mmap arrays were written to C:\Users\DiscoveryProteomics\AppData\Local\Temp\7\temp_mmap_6elyg_up. Cleanup of this folder is OS dependant, and might need to be triggered manually! Current space: 1,847,586,598,912

What could be the issue here?

I also attached a picture of the settings used. Thank you
![AlphaDIA_Custom_061724](https://github.com/MannLabs/alphadia/assets/91179678/337dc782-f23d-4b54-adb1-56d7cfa1d51e)

**Comment by jalew188** [comment]
@GeorgWa Potential bug on Windows: path with spaces

**Comment by GeorgWa** [comment]
Hi, yes, this seems to be an issue with parsing a path space in hte path. A quickfix would be to change the output folder to a location where there are no spaces in the path. We can fix this with the next version.
