### ISSUE TITLE
Installation of GUI on MacOS | ARM64/x64

### ISSUE THREAD

**Issue by lucas-diedrich** [MannLabs/alphadia#356]
During installation, I accidentally downloaded the wrong version of the alphaDIA GUI for MacOS (alphadia-xxx-macos-darwin-x64.pkg instead of alphadia-xxx-macos-darwin-arm64.pkg). It would be helpful to add a note to the installation instructions so that it is (even more obvious)/easier for users differentiate between Mac x64/Mac ARM64 architectures. 

The Mac architecture can be looked up by clicking on the Apple Symbol > About this Mac > Chip  (ARM64 for Mx chips, x64 for Intel chips)

**Comment by mschwoer** [comment]
thank you, updated here: https://github.com/MannLabs/alphadia/pull/401
