### ISSUE TITLE
ms1 and ms2 tolerance

### ISSUE THREAD

**Issue by wangss3** [MannLabs/alphadia#362]
Hi,

1. I have a sciex qtof 7600 and orbitrap HF. How can I know the optimal ms1 and ms2 tolerance. 
For qtof every time set as 0? 10ppm or 15ppm for Orbitrap?

2. Is there any function like DIA-NN's pipeline in window GUI? I have to run first and second search manualy every time?

Best,
Ko

**Comment by wangss3** [comment]
Use this optimized parameter for all future search?

`PROGRESS: Search parameter optimization finished. Values taken forward for search are:
2:50:50.152362 PROGRESS: ==============================================
2:50:50.152362 PROGRESS: ms2_error      : 5.3499
2:50:50.152362 PROGRESS: rt_error       : 1024.5078
2:50:50.162362 PROGRESS: ms1_error      : 9.2534
2:50:50.162362 PROGRESS: ==============================================`

**Comment by GeorgWa** [comment]
Hi, 

if you don't know, search a triplicate with MS2=0 and MS1=0. 
Then have a look at the stat.tsv table where the optimal value is reported.
You can also use the tolerance which was reported by DIA-NN.

To give you some intuition:
For ScieX 7600 I usually use 15ppm MS1 and MS2. 
For the Orbitrap it depends on the transient.
I would use 15-20ppm with 30k resolution, 10ppm for 60k resulution, 5ppm for 120k resolution (mostly MS1)

Leave RT optimization always on (RT=0).

I hope this helps,
Georg
