### ISSUE TITLE
No objects to concatenate (astral)

### ISSUE THREAD

**Issue by wangss3** [MannLabs/alphadia#367]
Hi,

I downloaded astral raw files and analyzed wiht library free search.
And here's the log file.
[log.txt](https://github.com/user-attachments/files/17660763/log.txt)

Best,
Ko

**Comment by GeorgWa** [comment]
Hi, 

it looks like there was an error with the rt limit for the optimization.
We will fix this and include it in the next version.

For now just set the `target_rt_tolerance = 20` which should prevent the error and give the same results.

Best,
Georg
