### ISSUE TITLE
dia-PASEF format

### ISSUE THREAD

**Issue by Li5459000** [MannLabs/alphadia#379]
Hi,

"Alltough search is possible, alphaDIA's feature-free search takes a long time with fully predicted libraries."

If speed is not a concern, would using library free search for dia-PASEF format compromise analytical performance, such as resulting in lower IDs?

**Comment by Li5459000** [comment]
How should I specify modifications beyond the default ones? I am using the GUI, but there doesn't seem to be a list of selectable modifications.

For example, if I want to set Methionine excision (N-term), how should I configure it?

Thank you in advance.

**Comment by GeorgWa** [comment]
It should have no or only very small impact on the analytical performance. If you have enough memory (64-128gb) feel free to try it. 

Methionine excision is always enabled in alphabase but we want to make this configurable in one of the next releases. 

You can find a list of all modifications here: https://github.com/MannLabs/alphabase/blob/main/alphabase/constants/const_files/modification.tsv

You can use a semicolon separated list in the GUI.
