### ISSUE TITLE
No objects to concatenate 1.8.2

### ISSUE THREAD

**Issue by wangss3** [MannLabs/alphadia#384]
Hi，

I analyzed previous dataset with version 1.8.2 but still got the same error. #367 
This bug fixed from 1.8.1 to 1.8.2?
[log.txt](https://github.com/user-attachments/files/17912103/log.txt)

Also, I have many WARNING: 
like "FDR calculation may be inaccurate as there is more than 10% difference in the number of target and decoy PSMs"

**Comment by GeorgWa** [comment]
Hi, It‘s already fixed on Github in the dev version but there hasn’t been a new release yet. You could always try the dev version: https://alphadia.readthedocs.io/en/latest/installation.html#developer-installation

I will make a new release this week👍🏻
